Initial 0.2.0.0 commission

diff --git a/bin/kezendiatail b/bin/kezendiatail
--- a/bin/kezendiatail
+++ b/bin/kezendiatail
@@ -41,29 +41,36 @@
 # Report any bugs to <bugs@paradisim.tk> or visit our FAQ on our website.
 #
  
+# as you can see, this is not started yet, but its here as a reminder to get it done some day
 
+[[ -z $GXBASE_ROOT ]] && { GXBASE_ROOT="$(readlink -e `dirname ${BASH_SOURCE}`/../../.)"; syslog "Note: Guessing GXBASE_ROOT = ${GXBASE_ROOT}."; }
+[[ ! -r ${GXBASE_ROOT}/startgxbase ]] && { echo "Error: you need GXBASE_ROOT pointing to the GXBASE script library for this to work!"; }
+# delegate to simplify handling of interactive mode scripting to keep variables local and keep 'exit' from actually exiting the caller's shell
+[[ -z ${-//[^i]} ]] && { eval $BASH_SOURCE "$@"; return $?; }
 
+# handle the script
 
+case "$0" in
+	dialog)
+		echo "dialog commands here"
+		;;
+	whiptail)
+		echo "whiptail commands here"
+		;;
+	choice)
+		echo "choice commands here"
+		;;	
+	kdialog)	
+		echo "kdialog commands here"
+		;;
+	zenity)
+		echo "zenity commands here"
+		;;
+		
+	*)	
+		echo "unsupported command"
+		;;
+esac
 
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
+echo "This script is not finished"
 
diff --git a/bin/makeblur b/bin/makeblur
--- a/bin/makeblur
+++ b/bin/makeblur
@@ -1,19 +1,73 @@
 #!/bin/bash
+
+function __makeblur()
+{
+unset -f $0
+unset PICK_WINDOW IGNORE_NOKDE
+ARGS=`getopt -n ${0//_/} -l help,pick,ignore-no-kde -o h?pi -- "$@"`
+[[ $? -ne 0 ]] && { echo "Usage: makeblur [-hpi? | --help --pick --ignore-no-kde] -- [xprop flags]"; return $?; }
+eval set -- "$ARGS"
+while [[ $1 != '--' ]]; do
+	case ${1//-/} in 
+		help|h)
+			cat <<-EOH
+			
+			Make the background of a terminal or other semi-transparent window blurry.
+			This requires KDE's kwin compositor in order to work with this script.
+
+			syntax: makeblur [-hpi? | --pick|--ignore-no-kde|--help] -- [xprop flags]
+
+			-p	--pick 
+			 \tdo not autodetect current window, your mouse pointer will change shape, then you must click on
+			\tthe window that you wish to apply the attributes to (or right-click to cancel). The button order
+				is reversed on left-handed mouse systems.
+			-i	--ignore-no-kde
+			    try to apply the attributes even if the window does not seem to carry the right kind of
+			    window attributes (forcefully apply) This does not guarentee that the window will be blurred!
+			-h	-?	--help
+				The text you are reading now
+
+			This script is distributed as part of the GXBASE repository and distribution and is licensed under
+			the LGPL versions 2 and above. Visit the GNU-GPL website for more information on this license.
+
+			EOH
+			return 0;;
+		pick|p)
+			PICK_WINDOW=1;;
+		ignore-no-kde|i)
+			IGNORE_NOKDE=1;;
+		*)
+			echo "internal error: $1 not expected at this time";;
+	esac
+	shift
+done
+unset getspec
+while [[ ! -z "$1" ]]; do
+	# process non-proc options
+	[[ $getspec ]] && [[ $getspec != -root ]] && echo "warning: xprops already set, being overwritten by later specs: $1";
+	getspec=$1
+	shift
+done
 if [ $DISPLAY ]; then
-	if ( ! xprop -root | grep KDE > /dev/null ); then
+	if ( ! xprop -root | grep KDE > /dev/null ) && [[ -z $IGNORE_NOKDE ]]; then
 		echo "MAKEBLUR: window type not KDE, cannot run."; false
 	else
 		function func_getcurrentwindow()
 		{
 			if (tty -s); then
-				getspec="-root"
+				if [[ $PICK_WINDOW ]]; then
+					unset getspec
+				else
+					getspec='-root'
+				fi			
 			else
-				getspec=
+				unset getspec
 			fi
-			xprop $getspec | grep ^"_NET_ACTIVE_WINDOW" | grep --only-matching "0x[0-9a-fA-F]*" --color=never			
+			eval xprop $getspec | grep ^"_NET_ACTIVE_WINDOW" | grep --only-matching "0x[0-9a-fA-F]*" --color=never			
 		}
 		
-		xprop  -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 -id `func_getcurrentwindow`
+		xprop -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 -id `func_getcurrentwindow`
+
 		RETVAL=$[ $? + 0 ]
 		# just in case we were sourced, undefine the function
 		unset func_getcurrentwindow
@@ -32,3 +86,7 @@ if [ $DISPLAY ]; then
 		fi
 	fi
 fi
+
+}
+
+__makeblur "$@"
diff --git a/bin/makex b/bin/makex
--- a/bin/makex
+++ b/bin/makex
@@ -1,1 +1,24 @@
-chmod 775 $*
+unset ADDOPT
+if [[ -d "$*" ]]; then
+	echo "$* is a directory, recurse it?"
+	if [[ $(read -sn1 r; printf $r) == y ]]; then
+		echo "okay, recursing.."
+		ADDOPT="--recursive"
+	else
+		echo "nevermind."
+	fi
+fi
+sudo chmod $ADDOPT ug+x $*
+if [[ $? -eq 0 ]]; then
+	declare -i a=0
+	if [[ $ADDOPT ]]; then
+		IFS='
+		'
+		# subtract for the . .. entry 
+    a=$[ $(find $* | grep -Po --count "^.*$") - 2 ];
+	else
+		for i in $@; do a+=1; done
+	fi
+	echo "Finished, $a item(s) made executable, without errors."
+fi
+
diff --git a/bin/mix b/bin/mix
--- a/bin/mix
+++ b/bin/mix
@@ -1,5 +1,8 @@
 #!/bin/bash
 #
+#  IF YOU GET ERRORS LIKE "Unable to find simple control ... blah blah Master,0" this means
+#   you NEED to set the DEFAULT_CARD and perhaps other variables (see below)
+#
 # /bin/mix
 #   
 #   change master volume setting based on the name of the link (this program's program_name)
@@ -41,9 +44,9 @@
 # to 1 (recommended), the card '1' will be tested, if it is there, it will be used, and if not, it will
 # fallback to 0. 
 #
-# IMPORTANT: if you dont know what your card is, please use card "1"
-#
-DEFAULT_CARD=1
+# IMPORTANT: if you dont know what your card is, please use card "0"
+#                 
+DEFAULT_CARD=0
 
 
 
@@ -144,6 +147,12 @@ fi
 
 echo "amixer -c $CARD sget Master | grep -Po stff" 
 CURVOL=`amixer -c $CARD sget Master | grep -Po '(?<=Playback )[0-9]+(?= \[)'`
+if [[ -z $CURVOL ]]; then
+	echo "FAILURE: cant get current volume from mixer, please set the VARIABLES in mix script to something valid, read the script for details"
+	return 1 > /dev/null 2>&1
+	exit 1
+fi
+
 if [ ! -z "$*" ]; then
 	# test for inline negatives or positives first
 	TEST="$1"
@@ -164,10 +173,10 @@ if [ ! -z "$*" ]; then
 	
   
   AMT=$[ $2 ]
-	if [ "$1" == "up" ] || [ "$1" == "+" ]; then
+	if [[ "$1" == "up" ]] || [[ "$1" == "+" ]]; then
 		#echo "COMMAND: UP   VALUE: $2"
 		NEWVOL=$[ $AMT + $CURVOL ]
-	elif [ "$1" == "down" ] || [ "$1" == "dn" ] || [ "$1" == "-" ]; then
+	elif [[ "$1" == "down" ]] || [[ "$1" == "dn" ]] || [[ "$1" == "-" ]]; then
 		#echo "COMMAND: DOWN  VALUE: $2"
 		NEWVOL=$[ $CURVOL - $AMT ]
 	else
