July 5 Updates to scripts, moved bin extras to bin, added stubs, etc

diff --git a/bin/vim b/bin/vim
--- a/bin/vim
+++ b/bin/vim
@@ -15,6 +15,9 @@
 case $- in *i*) eval $BASH_SOURCE "$@"; return $?;; esac
 # since security measures taken, $0 will be the script's name always
 
+# variables
+# SUDOTHRESH (integer): minimum number of files that need admin rights to read/write before sudo kicks in (default=1)
+declare -i SUDOTHRESH=1
 
 case $UID in
 0)
@@ -84,7 +87,7 @@ case $BASENAME in
 					echo "example: gen-sudo /usr/bin/sudoedit"
 					echo
 					echo "You MUST supply the full path to the program because it will be used to remove"
-					echo "it's entry from the hashtable in order to allow you to run this command anew."
+					echo "it's entry from the hash table in order to allow you to run this command anew."
 					echo "If you already have done this, just make sure $(dirname $BASH_SOURCE) is in"
 					echo "your system's path variable. Edit your ~/.bashrc to do this. See below for more."
 					echo
@@ -121,6 +124,14 @@ case $BASENAME in
 		esac
 		;;
 ############################## Place Program Route Filters Here ###############	
+## NOTICE: append routes with ;;& if you wish to continue execution
+##         use ;; to stop execution, or use ;& to execute the next block 
+##         UNCONDITIONALLY--if the ln) block ended with ;& then the ln)
+##         block would execute the vim) block as well, and since vim
+##         continues processing, it would inherit that behavior because of it.
+##         The route would be: ln->vim->[any other blocks and conditions]->*
+##         Please use this kind of routing with care!!
+
 			# ln route filter, checks for overwrite (accidental misnaming arguments) 
 			ln)				
 				if [[ $1 == "-s" ]]; then
@@ -136,8 +147,103 @@ case $BASENAME in
 			 		# continue
 
 					fi
-					;;&
-###############################################################################					
+					# routing to continue evaluating for possible route matches
+					;;& 
+			vim|gvim|vim.*)					
+				# vim route filter, simply checks the FILE components of the
+				# command string, checks to see if they are read only, and
+				# elevates if needed, with a brief warning.
+				# NOTE: switch values are ignored however, the values immediately following switches that may actually be attributed to switches
+				#       are not treated specially and could be misinterpreted as a false elevation case, in which case you should run vim directly
+				#       or use the -direct as your first parameter afterwards. Example: vim -direct --vim-option vim-option-string file1 ...
+				#       Beware that if you do this, there will be no elevation, that is why there is also a "vim -directsudo" argument, which works
+				#       the same way except sudo is used by force:
+				declare -i SUDOCOUNT=0
+				case $1 in
+					"-directsudo")
+							((SUDOCOUNT++))							
+							;&
+					"-direct")
+							SKIPCHECKS=1
+							shift
+							;;
+					*)															
+							for i in "$@"; do
+								# do not process switch values
+								if [[ "${i: 0:1}" == "-" ]]; then
+									continue
+								fi
+								if [[ -e "$i" ]]; then
+									# exists, check for write-ability/readability
+									if [[ ! -r "$i" ]] || [[ ! -w "$i" ]]; then
+										((SUDOCOUNT++))
+									fi
+								else
+									# check for the file in PATH and VIM_SEARCHPATH (see default above)
+									# dont walk through the PATH, make a temporary copy and possibly reinject
+									# original copy to be restored after looking
+	#						#	OLD_PATH=$PATH									
+ #						 # 	[[ "$VIM_SEARCHPATH" == "" ]] && unset VIM_SEARCHPATH  # the next will fail if its empty but still set, correct that here 									
+#	 IN PROGRESS	#						# note the +: which will only add the searchpath and the : preceding it if it is not empty
+#								# PATH=$PATH${VIM_SEARCHPATH+:}${VIM_SEARCHPATH}
+ #						# 	MATCH=$(type -p "$i")
+									
+
+									# doesn't	exist, check target's directory
+									ITEMDIR=$(dirname "$i")							
+									if [[ -d "$ITEMDIR" ]] && [[ ! -w "$ITEMDIR" ]]; then
+										((SUDOCOUNT++))
+									elif [[ -d "$ITEMDIR" ]] && [[ ! -r "$ITEMDIR" ]]; then
+										((SUDOCOUNT++))						
+									fi
+								fi
+							done
+							;;
+				esac
+				VIMDESTS=($(type -pa $BASENAME))
+				# default if no other found
+				VIMSPEC=/usr/bin/vim
+				unset VIMFOUND
+				for kk in "${VIMDESTS[@]}"; do
+					echo "comparing $kk against $BASH_SOURCE..."
+					if [[ $kk != $BASH_SOURCE ]]; then
+						echo "found one: $kk"
+						VIMSPEC=$kk
+						VIMFOUND=1
+						break
+					fi
+				done
+				[[ $VIMFOUND != 1 ]] &&	echo "Warning, could not find a copy of vim in your path, using the default: $VIMSPEC"			
+				############### boundary check ######################
+				
+				# at  this point, there is a chance that the user may have 
+				# double linked the vim in different locations, if this is 
+				# the  case we cant have it  running forever in a loop, we 
+				# will detect this and warn the  user so that he,  she, or 
+				# it can resolve the issue:
+
+				if [[ $VIM_RUNNING ]]; then
+					echo "Error: infinite loop protection, terminating without running."
+				else
+          export VIM_RUNNING=1
+					if [[ $SUDOCOUNT -ge $SUDOTHRESH ]]; then
+						# one or more files tagged, and the tag threshold has been met
+						[[ $SKIPCHECKS ]] && echo -ne "User evoked switcharg-ignoring \"directsudo\", " || echo -ne "One or more file system	object(s) are inaccessible, "
+						echo "using root privileges."
+						sleep 2						
+						sudo -H "$VIMSPEC" "$@"
+					else
+            [[ $SKIPCHECKS ]] && echo -ne "User evoked switcharg-ignoring \"direct\": "
+						echo "Editing using ${USERNAME}'s permissions."
+						sleep 1						
+						"$VIMSPEC" "$@"
+					fi
+					unset VIM_RUNNING
+				fi
+				exit $?
+
+				
+    	;;
 	*)
 		[[ ! -r ~/.hushgen ]] && [[ -z $NOQUOTE ]] && echo "[0;36m--- [1msudo $BASENAME $* [21m---[0m" || HUSH=1
 		eval sudo "$BASENAME" "$@"
diff --git a/res/bash-helpers b/res/bash-helpers
--- a/res/bash-helpers
+++ b/res/bash-helpers
@@ -12,13 +12,30 @@
 #
 # guioff - enabled/disables GUI features of commands that support this variable
 #
+
+
 function guioff()
 {
-	if [[ $NOGUI ]]; then		
-		unset NOGUI
-	else
-		export NOGUI=on
+  [[ -z $1 ]] && set toggle
+	case $1 in
+		toggle)
+			[[ $NOGUI ]] && unset NOGUI || NOGUI=1
+			;;
+		on)
+			[[ $NOGUI ]] || NOGUI=1
+			;;
+		off)
+			[[ $NOGUI ]] && unset NOGUI			
+			;;
+	esac	
+
+
+	if [[ -z $NOGUI ]]; then				
+		echo "Commands are now oblivious to GUI-disabling effects of guioff"	
+	else	
+		echo "Commands that support GxBase GUI-disabling are now: disabled"
 	fi;
+
 	echo "GUI commands are now ${NOGUI-off}."
   [[ $NOGUI ]] && return 0
 	return 1	
@@ -469,6 +486,28 @@ function startx()
 	return $ERR
 }
 
+function hashdir()
+{
+	shopt -s nullglob
+
+	if [[ -z $1 ]] || [[ ! -d $1 ]] || [[ -z $1/* ]]; then
+		echo "error: need to specify an existing directory that contains FILES"
+	else		
+		pushd . &> /dev/null
+		cd $1 &> /dev/null
+		if [[ $? -eq 0 ]]; then
+			for i in *; do
+				echo "hashing $PWD/$i to command '$i'..."
+				hash -p $PWD/$i $i
+			done
+		else
+			echo "error while or after switching to: $1"
+		fi		
+		popd &> /dev/null		
+	fi
+}
+
+
 # loadhashes [workdir] [target]
 function loadhashes()
 {
@@ -479,7 +518,7 @@ function loadhashes()
 		return 0
 	fi
 	local IFS=$'\n'
-	for i in $(echo $1/$2.hash); do
+	for i in $(cat $1/$2.hash); do
 		hash -p "$1/$2" "$i"
 	done
 
@@ -500,7 +539,7 @@ function hashautocmd()
   {  
   for i in *; do 
     if [[ "$(basename "$(readlink "$i")")" == "$2" ]]; then 
-	echo $i; 
+			echo $i; 
     fi; 
   done
   } > "$2.hash"
diff --git a/res/temp b/res/temp
--- a/res/temp
+++ b/res/temp
@@ -10,6 +10,23 @@
 # - do not delete this file or truncate it when redistributing the package, all developers should have access to this information, miniscule as it may seem
 #
 # created 2-May 2014 - updated 3-May 2014 first released with gxbase v0.2.0-1 (alpha)
+# updated 5-Jun 2014: added commands: dirof, cdof  updated command: findwithchildren (fixed missing $* bug, was missing the $)
+#                     fixed documentation block for ownercount()
+# latest version of this file and gxbase is available from: git://gitorious.org/gxbase/0-2-0.git
+# this file was incepted into the repository starting at branch: 0.2.0.0
+#                                     last documentation branch: 0.2.0.1
+
+# Licensed under the GNU GPL (NOT LGPL as previously licensed)
+
+
+# cuts down permission blocks into single letter codes
+# ie: e = only executable(1)           W=only writable(2)       R=only readable(4)  X=read/execute(5)
+#     A = read/write/executable(7)     B=both read/writable(6)  N=none(0)           E=write/execute(3)
+function shortls()
+{
+	ls -l "$@" | colrm 30 42 | colrm 11 12 | sed "s/-wx/E/g;s/rwx/A/g;s/r-x/X/g;s/--x/e/g;s/rw-/B/g;s/r--/R/g;s/-w-/W/g;s/^l/^[[33m/g;s/^d/^[[32m/g;s/^-/^[[0m/g"
+}
+
 
 # get count of ownership for a set of files
 # ie:  6 owned by root:root 24 owned by www:users, 1 owned by root:daemon, etc
@@ -254,10 +271,14 @@ function makebusyboxlinkshere()
 	return 0
 }					
 
+# findwithchildren DIRECTORYNAME
+# DIRECTORYNAME can be partial
+# finds a directory and sees if it has more subdirs, if so returns them (the directory children, NOT the directory)
+# in stdout (usually, fd0)
 function findwithchildren()
 {
 	declare -i FOUNDCOUNT=0
-	for i in `dirname $(locate *) | sort | uniq`; do 
+	for i in `dirname $(locate $*) | sort | uniq`; do 
 		for ((j=1;j<=#;j++)); do
 			FOUNDCOUNT=0
 			if [[ -d "$i/${!j}" ]]; then
@@ -270,7 +291,7 @@ function findwithchildren()
 	done
 }
 
-# colorize [topic]
+# colorize TOPIC
 function colorize()
 {
 	TOPIC="$*"
@@ -280,3 +301,35 @@ function colorize()
 	fi
 	/bin/sed -r "s/$TOPIC/[32;1m\0[0m/g;s/[^\s0-9]*:/[1m\0[0m/g;s/[\:\.\<\>\(\)\=\/\,]/[30;1m\0[0m/g"
 }	
+
+# dirof command   - any binary or executable script in $PATH (even if aliased/functioned over!) 
+# very handy -- next func shows why
+function dirof() 
+{ 
+	dirname $(type -fap "$@")
+}
+# cdof [-push] command - change to directory where "command" is
+#                        if "command" is not found, then it searches
+#                        for a location of anything matching that name, 
+#                        case insensitive. Use -push to push the dir first!
+function cdof()
+{
+	[[ $1 == -push ]] && { pushd . &> /dev/null; shift; local NEEDPOP=YES; }
+	if [[ $(dirof $*) ]]; then
+		cd $(dirof "$*")
+		if [[ $? -eq 0 ]]; then return 0;fi
+	else
+	# try to find approximate match for
+		cd $(dirname $(find -l1 --ignore-case "$*"))
+		if [[ $? -eq 0 ]]; then return 0;fi
+	fi
+	ERRC=$?
+	# failed, pop back if pushed
+	[[ $NEEDPOP == YES ]] && popd &> /dev/null	
+	# return error code, but only if it was set (if not set to 1 to indicate that there was a definite error)
+	case $ERRC in
+		0) return 1;;
+		*) return $ERRC;;
+	esac
+}
+
