May Week 4 End-of-Week (Fri) Updates

diff --git a/res/gxcmd b/res/gxcmd
--- a/res/gxcmd
+++ b/res/gxcmd
@@ -42,11 +42,6 @@ case $- in 	*i*) 	alias exit="unalias exit;return";; esac
 
 # 1 primary stuff, must be first because it is used by this file too (and most other components!)
 
-
-
-
-
-
  
 
 # uniqsessidv (echos to stdout)
@@ -71,67 +66,117 @@ function uniqsessidv()
 # experimental (you may need to edit your /etc/sensors.conf to get this to work right)
 function cputemp()
 {
-	if [[ $# -gt 1 ]]; then
-		echo "too many arguments"
-	elif [[ $# -eq 0 ]]; then
-		set -- -h
-	fi
-	case $1 in
-		-h)
-			ISHORIZ=1;;
-		-v)
-			unset ISHORIZ;;
-		*)
-			echo "bad options: $1, must be -h or -v (or none)"
-			return 1;;
-	esac
+	unset FLGS NODEC
+  ARGS=`getopt -n $FUNCNAME-${LINENO[*]} -o fdhzvi: -l no-decimal,fahrenheit,help,horiz,vert,index: -- "$@"`
+	[[ $? -ne 0 ]] &&	return $?
+	declare -i IDX=0
+	eval set -- "$ARGS"
+	while [[ $1 != '--' ]]; do
+		case ${1//-/} in
+			h|help)
+				echo "$BASH_SOURCE -- $0 -hzv -i[= ][index] -fd --horiz --vert --index [index] --fahrenheit --no-decimal"
+				return 0
+				;;
+			z|horiz)
+				ISHORIZ=1
+				;;
+			f|fahrenheit)
+				FLGS="-f"
+				;;
+			v|vert)
+				unset ISHORIZ
+				;;
+			i|index)
+				IDX=$2
+				((IDX++))
+				# one more for $2 as well
+				shift 
+				;;
+			d|nodecimal)
+				NODEC=1
+				;;
+			*)
+				echo "internal error: $0 [$1]"
+				return 126
+				;;
+		esac
+		shift
+	done	
 	# TODO: need to tweak color for ALARM states but didnt add it, it doesnt work for things like the STDOUT plasmoid
 	#       maybe add a flag for colorized temps at alarm state (and maybe need a COLOR STDOUT plasmoid, or cairodock, etc)
-	if [[ $ISHORIZ ]]; then
-		sensors | grep -P "(temp[0]|Mainboard|CPU [12]|thermistor)" | grep -P "\s\s+[-+][0-9]{1,3}...[CF]" -o | tr -d ' ' | tr '\n' ' '
-		unset ISHORIZ
+ 	for i in `sensors $FLGS | grep -P "(temp[0]|Mainboard|CPU [12]|thermistor)" | grep -P "\s\s+[-+][0-9]{1,3}...[CF]" -o | tr -d ' '`; do 	
+		if [[ $NODEC == 1 ]]; then
+			ITEMS+=(${i//\.[0123456789]/})
+		else
+ 			ITEMS+=($i)
+		fi
+	done
+	
+	# debug: echo -en "\nITEMS: ${ITEMS[*]}   IDX: $IDX  ISHORIZ: ${ISHORIZ-not set}"
+	if [[ $IDX -gt 0 ]] && [[ $IDX -le ${#ITEMS[@]} ]]; then
+		# convert back to 0-based for actual use
+		echo -ne "${ITEMS[IDX-1]}"
 	else
-		sensors | grep -P "(temp[0]|Mainboard|CPU [12]|thermistor)" | grep -P "\s\s+[-+][0-9]{1,3}...[CF]" -o | tr -d ' '
+		if [[ $IDX -ge ${#ITEMS[@]} ]]; then
+			echo "INDEX out of range ($IDX), displaying all values!"
+		fi
+		ISFIRST=1
+		for ((j=${#ITEMS[@]};j>=0;j--)); do
+			if [[ -z $ISFIRST ]]; then
+				if [[ $ISHORIZ == 1 ]]; then
+					echo -ne " "
+				else
+					echo -ne "\n"
+				fi
+			else
+				unset ISFIRST
+			fi
+			echo -ne "${ITEMS[$j]}"
+		done
 	fi
 	return $?
 }
 
-CMD_VALID=0
-for CMD in help `cat $BASH_SOURCE | grep -Po "(?<=function )[^\(]*"`; do
-	if [[ $1 == $CMD ]]; then
-		CMD_VALID=1
+ARGS=`getopt -l help -o h -n gxcmd -- "$@"`
+if [[ $? == 0 ]]; then
+	eval set -- "$ARGS"
+	while [[ $1 != "--" ]]; do
+		case $1 in
+			--help|-h)
+				echo "help placeholder here"
+				exit 0
+				;;
+			*)
+				echo "internal error near argument $1"
+				exit 254
+				;;
+		esac
 		shift
-		break
-	fi
-done
-if [[ $CMD_VALID -eq 1 ]]; then
-	if [[ $CMD == help ]]; then
-		
-		exit 0
-	else
-		# function command
-		$CMD "$@"
-		exit $?
-	fi
-else
-	CMD_STATUS=${1+empty}${1=bad}
-	echo "Bad command given ($1)"dd
-	
-
-fi
-
-
-
-if [[ $1 ]] && [[ $1 != help ]]; then
-	CMD=$1
+	done
 	shift
-	case $CMD in 
-		cputemp) cputemp "$@";;
-	      	*) echo "invalid command: $CMD"; exit 1;;
-	esac
-else
-	echo "available commands: help cputemp"
 
+	CMD_VALID=0
+	for CMD in help `cat $BASH_SOURCE | grep -Po "(?<=function )[^\(]*"`; do
+		if [[ $1 == $CMD ]]; then
+			CMD_VALID=1
+			shift
+			break
+		fi
+	done
+
+	if [[ $CMD_VALID -eq 1 ]]; then
+		if [[ $CMD == help ]]; then
+			echo "help not available yet"
+			exit 0
+		else
+			# function command
+			$CMD "$@"
+			exit $?
+		fi
+	else
+		echo "Bad command given ($1)"
+	fi
+else
+	exit 2
 fi
-		
 
